### ISSUE TITLE
[Question] Question about labwidget

### ISSUE THREAD

**Issue by mphirke** [davidbau/rewriting#1]
Hello, first of all, great work but even better way of using Colab for the demo. I am having a lot of fun changing things into trees and horse mouths.

I could not find a license for labwidget or this repo in general on both Github and the linked MIT website. Is it possible for me to use labwidget for some of my notebooks with proper citations/credit? I've wanted to host stylegan models on the web but Heroku doesn't provide GPUs and the ones that do cost money while Colab is free.

**Comment by davidbau** [comment]
Absolutely, you can reuse it with attribution.  I'll add a license to the
repo today.

David

**Comment by mphirke** [comment]
Thank you very much for a quick response and for the permission.
