### ISSUE TITLE
Rendering in isolation from neighbouring features

### ISSUE THREAD

**Issue by vidit98** [davidbau/rewriting#9]
Hi, I found the idea of seeing weights as associative memory very interesting. Could you please explain in some more detail what do you mean by rendering feature patch in isolation from neighboring features? 

For example, if a network generates an output of 256x256 and I want to generate an isolated patch of 32x32. If we are analyzing a layer L with feature maps with spatial size 32x32, should the features excluding a 4x4 patch be set to 0 and so on for other layers to get final output?

**Comment by davidbau** [comment]
That is exactly right.
